# Generated by Django 3.0.3 on 2020-05-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='eType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(max_length=20)),
                ('e_description', models.CharField(max_length=200)),
                ('e_city', models.CharField(max_length=20)),
                ('e_date', models.DateField()),
                ('e_time', models.TimeField()),
                ('e_capacity', models.IntegerField(max_length=10)),
                ('e_attending', models.IntegerField(max_length=10)),
                ('e_vacancy', models.IntegerField(max_length=10)),
                ('e_price', models.IntegerField(max_length=10)),
                ('e_duration', models.IntegerField(max_length=10)),
                ('e_sales', models.IntegerField(max_length=10)),
                ('e_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addevent.eStatus')),
                ('e_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addevent.eType')),
            ],
        ),
    ]
