# Generated by Django 3.0.3 on 2020-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='e_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
