# Generated by Django 3.0.3 on 2020-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0003_auto_20200514_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='e_date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='e_time',
        ),
        migrations.AlterField(
            model_name='events',
            name='e_attending',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_sales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='e_vacancy',
            field=models.IntegerField(),
        ),
    ]
