# Generated by Django 3.0.3 on 2020-05-14 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0004_auto_20200514_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='e_date',
            field=models.DateField(default='2020-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='e_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
