# Generated by Django 3.0.3 on 2020-05-25 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0006_rsvp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='e_attending',
        ),
        migrations.RemoveField(
            model_name='events',
            name='e_description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='e_duration',
        ),
        migrations.RemoveField(
            model_name='events',
            name='e_sales',
        ),
    ]
