# Generated by Django 3.0.3 on 2020-05-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0007_auto_20200524_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='e_attending',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='e_description',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='events',
            name='e_duration',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='e_sales',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
