# Generated by Django 3.0.3 on 2020-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0008_auto_20200524_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='e_attending',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
