# Generated by Django 3.0.3 on 2020-05-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0009_auto_20200524_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='e_description',
        ),
    ]
