# Generated by Django 3.0.3 on 2020-05-25 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addevent', '0012_auto_20200524_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addevent.Events'),
        ),
    ]
